default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: paper_app_development
  username: postgres
  password: 998915309764
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout:  5000

development:
  <<: *default

test:
  <<: *default
  database: paper_app_test

production:
  # <<: *default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 100
