default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV.fetch('PGDATABASE') %>
  username: postgres
  password: 998915309764
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout:  5000

development:
  <<: *default
  # adapter:  postgresql
  # encoding: unicode
  # database: railway
  # host: postgres.railway.internal
  # username: postgres
  # port: 56155
  # password: WFeOMkKlNmpmSDrfDLMEOuZYYuwGiVkU
  # url: postgresql://postgres:WFeOMkKlNmpmSDrfDLMEOuZYYuwGiVkU@gondola.proxy.rlwy.net:54901/railway
  # pool: 100
test:
  <<: *default
  database: global_gm_test

production:
  adapter:  postgresql
  encoding: unicode
  database: <%= ENV["PGDATABASE"] %>
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV["PGUSER"] %>
  port: <%= ENV["PGPORT"] %>
  password: <%= ENV["PGPASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>
  pool: 100
